### PR TITLE
README.md: typo

### PR DESCRIPTION
**Pull request by Thomas-Gelf**

### CODE REVIEW

**Review by WyriHaximus — APPROVED** [review]
Good catch thanks :+1: , need to do a better readme anyway tbh :zipper_mouth_face: 

P.S. I belive the correct work for it is a `typo` not a `type` but I really appreciate it in this context :heart:

**Comment by Thomas-Gelf** [comment]
Typo fix with typo :rofl:

**Comment by Thomas-Gelf** [comment]
Force-pushed, no more typo in the typo :angel:

**Comment by WyriHaximus** [comment]
Thanks for the update :+1:

**Pull request merged**
